"""Add Collaboration models

Revision ID: 1bb984a640b4
Revises: f5d4ff42b249
Create Date: 2026-06-28 08:05:02.957014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb984a640b4'
down_revision: Union[str, Sequence[str], None] = 'f5d4ff42b249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaboration_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('leader', sa.String(), nullable=True),
    sa.Column('current_phase', sa.Enum('CREATED', 'PLANNING', 'TEAM_FORMATION', 'DELEGATION', 'EXECUTION', 'NEGOTIATION', 'CONSENSUS', 'VERIFICATION', 'COMPLETED', 'CANCELLED', 'FAILED', name='sessionphase'), nullable=True),
    sa.Column('shared_workspace', sa.JSON(), nullable=True),
    sa.Column('decisions', sa.JSON(), nullable=True),
    sa.Column('conflicts', sa.JSON(), nullable=True),
    sa.Column('negotiations', sa.JSON(), nullable=True),
    sa.Column('audit_log', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_collaboration_sessions_session_id'), 'collaboration_sessions', ['session_id'], unique=False)
    op.create_table('collaboration_messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('collaboration_id', sa.String(), nullable=True),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('receiver', sa.String(), nullable=True),
    sa.Column('message_type', sa.Enum('QUESTION', 'ANSWER', 'PROPOSAL', 'COUNTER_PROPOSAL', 'DECISION', 'APPROVAL', 'NOTIFICATION', 'WARNING', 'EVIDENCE', 'INFORMATION', name='messagetype'), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaboration_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_collaboration_messages_collaboration_id'), 'collaboration_messages', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_collaboration_messages_message_id'), 'collaboration_messages', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collaboration_messages_message_id'), table_name='collaboration_messages')
    op.drop_index(op.f('ix_collaboration_messages_collaboration_id'), table_name='collaboration_messages')
    op.drop_table('collaboration_messages')
    op.drop_index(op.f('ix_collaboration_sessions_session_id'), table_name='collaboration_sessions')
    op.drop_table('collaboration_sessions')
    # ### end Alembic commands ###
