"""Add Governance Workflow States

Revision ID: 8b76718ce3b8
Revises: 1bb984a640b4
Create Date: 2026-06-28 09:24:24.688647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b76718ce3b8'
down_revision: Union[str, Sequence[str], None] = '1bb984a640b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE workflowstatus ADD VALUE IF NOT EXISTS 'WaitingForGovernance'")
    op.execute("ALTER TYPE workflowstatus ADD VALUE IF NOT EXISTS 'Approved'")
    op.execute("ALTER TYPE workflowstatus ADD VALUE IF NOT EXISTS 'Rejected'")
    op.execute("ALTER TYPE workflowstatus ADD VALUE IF NOT EXISTS 'Blocked'")
    op.execute("ALTER TYPE workflowstatus ADD VALUE IF NOT EXISTS 'Resumed'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
