"""Initial workflows schema

Revision ID: f5d4ff42b249
Revises:
Create Date: 2026-06-28 07:38:51.242833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f5d4ff42b249"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_tenant_id"), "sessions", ["tenant_id"], unique=False
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_tenant_id"), "conversations", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_conversations_session_id"),
        "conversations",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("importance", sa.Float(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_tenant_id"), "messages", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_messages_conversation_id"),
        "messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_messages_role"), "messages", ["role"], unique=False)
    op.create_table(
        "conversation_summaries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_summaries_tenant_id"),
        "conversation_summaries",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_summaries_conversation_id"),
        "conversation_summaries",
        ["conversation_id"],
        unique=False,
    )
    op.create_table(
        "memory_entities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memory_relationships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workflows",
        sa.Column("workflow_id", sa.String(), nullable=False),
        sa.Column("workflow_version", sa.Integer(), nullable=True),
        sa.Column("template_name", sa.String(), nullable=True),
        sa.Column("template_version", sa.Integer(), nullable=True),
        sa.Column("goal", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("owner_agent", sa.String(), nullable=True),
        sa.Column("initiated_by", sa.String(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PLANNED",
                "READY",
                "RUNNING",
                "WAITING_FOR_APPROVAL",
                "PAUSED",
                "RETRYING",
                "COMPLETED",
                "CANCELLED",
                "FAILED",
                name="workflowstatus",
            ),
            nullable=True,
        ),
        sa.Column("approval_required", sa.Boolean(), nullable=True),
        sa.Column("workflow_metadata", sa.JSON(), nullable=True),
        sa.Column("execution_metrics", sa.JSON(), nullable=True),
        sa.Column("audit_log", sa.JSON(), nullable=True),
        sa.Column("dependencies", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("workflow_id"),
    )
    op.create_index(
        op.f("ix_workflows_workflow_id"), "workflows", ["workflow_id"], unique=False
    )
    op.create_table(
        "workflow_tasks",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("workflow_id", sa.String(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum(
                "CAPABILITY",
                "AGENT",
                "DECISION",
                "APPROVAL",
                "NOTIFICATION",
                "CONDITIONAL",
                "PARALLEL",
                "DELAY",
                "LOOP",
                name="tasktype",
            ),
            nullable=True,
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("assigned_agent", sa.String(), nullable=True),
        sa.Column("required_capability", sa.String(), nullable=True),
        sa.Column("dependencies", sa.JSON(), nullable=True),
        sa.Column("retry_policy", sa.JSON(), nullable=True),
        sa.Column("timeout", sa.Integer(), nullable=True),
        sa.Column("inputs", sa.JSON(), nullable=True),
        sa.Column("outputs", sa.JSON(), nullable=True),
        sa.Column("artifacts", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "QUEUED",
                "RUNNING",
                "RETRYING",
                "COMPLETED",
                "FAILED",
                "SKIPPED",
                "CANCELLED",
                name="taskstatus",
            ),
            nullable=True,
        ),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("execution_time", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.workflow_id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_workflow_tasks_task_id"), "workflow_tasks", ["task_id"], unique=False
    )
    op.create_table(
        "memory_objects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("memory_type", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("importance", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("memory_status", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("source_message_id", sa.UUID(), nullable=True),
        sa.Column("source_conversation_id", sa.UUID(), nullable=True),
        sa.Column("source_document_id", sa.String(), nullable=True),
        sa.Column("source_type", sa.String(), nullable=True),
        sa.Column("extracted_by", sa.String(), nullable=True),
        sa.Column("extraction_version", sa.String(), nullable=True),
        sa.Column("retrieval_count", sa.Integer(), nullable=True),
        sa.Column("last_accessed", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("embedding_required", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_objects_conversation_id"),
        "memory_objects",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_objects_memory_type"),
        "memory_objects",
        ["memory_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_objects_user_id"), "memory_objects", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_conversation_summaries_conversation_id"),
        table_name="conversation_summaries",
    )
    op.drop_index(
        op.f("ix_conversation_summaries_tenant_id"), table_name="conversation_summaries"
    )
    op.drop_table("conversation_summaries")
    op.drop_index(op.f("ix_messages_role"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_tenant_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_conversations_session_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_tenant_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_tenant_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_memory_objects_user_id"), table_name="memory_objects")
    op.drop_index(op.f("ix_memory_objects_memory_type"), table_name="memory_objects")
    op.drop_index(
        op.f("ix_memory_objects_conversation_id"), table_name="memory_objects"
    )
    op.drop_table("memory_objects")
    op.drop_index(op.f("ix_workflow_tasks_task_id"), table_name="workflow_tasks")
    op.drop_table("workflow_tasks")
    op.drop_index(op.f("ix_workflows_workflow_id"), table_name="workflows")
    op.drop_table("workflows")
    op.drop_table("memory_relationships")
    op.drop_table("memory_entities")
    # ### end Alembic commands ###
