from enum import Enum


class Capability(str, Enum):
    """
    Capabilities representing specific domain expertise an Executive Agent possesses.
    """

    CODE_REVIEW = "CODE_REVIEW"
    ARCHITECTURE_ANALYSIS = "ARCHITECTURE_ANALYSIS"
    DOCUMENT_ANALYSIS = "DOCUMENT_ANALYSIS"
    TECHNICAL_PLANNING = "TECHNICAL_PLANNING"
    RISK_ANALYSIS = "RISK_ANALYSIS"
    SECURITY_REVIEW = "SECURITY_REVIEW"
    SYSTEM_DESIGN = "SYSTEM_DESIGN"
    REPORT_GENERATION = "REPORT_GENERATION"
    STRATEGIC_LEADERSHIP = "STRATEGIC_LEADERSHIP"
    OPERATIONS_LEADERSHIP = "OPERATIONS_LEADERSHIP"
    FINANCIAL_LEADERSHIP = "FINANCIAL_LEADERSHIP"
    MARKETING_LEADERSHIP = "MARKETING_LEADERSHIP"
    HUMAN_RESOURCES_LEADERSHIP = "HUMAN_RESOURCES_LEADERSHIP"
    LEGAL_LEADERSHIP = "LEGAL_LEADERSHIP"
    SECURITY_LEADERSHIP = "SECURITY_LEADERSHIP"
    INFORMATION_LEADERSHIP = "INFORMATION_LEADERSHIP"
    PRODUCT_LEADERSHIP = "PRODUCT_LEADERSHIP"
    KNOWLEDGE_SYNTHESIS = "KNOWLEDGE_SYNTHESIS"
    RESEARCH_SYNTHESIS = "RESEARCH_SYNTHESIS"
    PLANNING_SYNTHESIS = "PLANNING_SYNTHESIS"
    ANALYTICS_SYNTHESIS = "ANALYTICS_SYNTHESIS"
