from app.agents.base.registry import AgentRegistry
from app.agents.executives.cto.agent import CTOAgent
from app.agents.executives.enterprise_agents import (
    AnalyticsAgent,
    CEOAgent,
    CFOAgent,
    CIOAgent,
    CISOAgent,
    CLOAgent,
    CMOAgent,
    COOAgent,
    CPOAgent,
    CSOAgent,
    CHROAgent,
    KnowledgeAgent,
    PlanningAgent,
    ResearchAgent,
)


def build_default_executive_registry(
    llm_service,
    capability_executor=None,
    knowledge_agent_graph=None,
):
    registry = AgentRegistry()

    registry.register_agent(
        CTOAgent(
            llm_service=llm_service,
            capability_executor=capability_executor,
            knowledge_agent_graph=knowledge_agent_graph,
        )
    )
    registry.register_agent(
        CEOAgent(
            llm_service=llm_service,
            capability_executor=capability_executor,
            knowledge_agent_graph=knowledge_agent_graph,
        )
    )
    registry.register_agent(
        COOAgent(
            llm_service=llm_service,
            capability_executor=capability_executor,
            knowledge_agent_graph=knowledge_agent_graph,
        )
    )
    registry.register_agent(
        CFOAgent(
            llm_service=llm_service,
            capability_executor=capability_executor,
            knowledge_agent_graph=knowledge_agent_graph,
        )
    )
    registry.register_agent(
        CMOAgent(
            llm_service=llm_service,
            capability_executor=capability_executor,
            knowledge_agent_graph=knowledge_agent_graph,
        )
    )
    registry.register_agent(
        CHROAgent(
            llm_service=llm_service,
            capability_executor=capability_executor,
            knowledge_agent_graph=knowledge_agent_graph,
        )
    )
    registry.register_agent(
        CLOAgent(
            llm_service=llm_service,
            capability_executor=capability_executor,
            knowledge_agent_graph=knowledge_agent_graph,
        )
    )
    registry.register_agent(
        CISOAgent(
            llm_service=llm_service,
            capability_executor=capability_executor,
            knowledge_agent_graph=knowledge_agent_graph,
        )
    )
    registry.register_agent(
        CIOAgent(
            llm_service=llm_service,
            capability_executor=capability_executor,
            knowledge_agent_graph=knowledge_agent_graph,
        )
    )
    registry.register_agent(
        CSOAgent(
            llm_service=llm_service,
            capability_executor=capability_executor,
            knowledge_agent_graph=knowledge_agent_graph,
        )
    )
    registry.register_agent(
        CPOAgent(
            llm_service=llm_service,
            capability_executor=capability_executor,
            knowledge_agent_graph=knowledge_agent_graph,
        )
    )
    registry.register_agent(
        KnowledgeAgent(
            llm_service=llm_service,
            capability_executor=capability_executor,
            knowledge_agent_graph=knowledge_agent_graph,
        )
    )
    registry.register_agent(
        ResearchAgent(
            llm_service=llm_service,
            capability_executor=capability_executor,
            knowledge_agent_graph=knowledge_agent_graph,
        )
    )
    registry.register_agent(
        PlanningAgent(
            llm_service=llm_service,
            capability_executor=capability_executor,
            knowledge_agent_graph=knowledge_agent_graph,
        )
    )
    registry.register_agent(
        AnalyticsAgent(
            llm_service=llm_service,
            capability_executor=capability_executor,
            knowledge_agent_graph=knowledge_agent_graph,
        )
    )
    return registry
