# Timeouts
DEFAULT_REQUEST_TIMEOUT = 30.0
LONG_REQUEST_TIMEOUT = 120.0
DB_CONNECTION_TIMEOUT = 5.0

# Retries
DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_BACKOFF = 1.0
MAX_RETRY_BACKOFF = 30.0

# Pagination
DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 1000

# String Literals
SYSTEM_USER_ID = "system"
ADMIN_ROLE = "admin"
USER_ROLE = "user"
