from typing import List, Dict, Optional
from pydantic import BaseModel, Field
from datetime import datetime, timezone
from enum import Enum


class DecisionStrategy(str, Enum):
    MAJORITY_VOTE = "MAJORITY_VOTE"
    WEIGHTED_VOTE = "WEIGHTED_VOTE"
    CEO_OVERRIDE = "CEO_OVERRIDE"
    CONSENSUS_REQUIRED = "CONSENSUS_REQUIRED"
    ADVISORY_ONLY = "ADVISORY_ONLY"


class ExecutiveDecision(BaseModel):
    """
    Structured response generated by the Executive Council.
    """

    objective: str
    decision_strategy: DecisionStrategy
    recommendations: List[str] = Field(default_factory=list)
    conflicts_detected: List[str] = Field(default_factory=list)
    votes: Dict[str, str] = Field(default_factory=dict)
    risks: Dict[str, List[str]] = Field(
        default_factory=dict,
        description="Categorized risks (e.g., Technical, Financial)",
    )
    confidence_score: float = Field(default=0.0)
    follow_up_actions: List[str] = Field(default_factory=list)
    participating_executives: List[str] = Field(default_factory=list)
    final_decision: Optional[str] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = {"from_attributes": True}
